plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '9.0.0-beta12'
}

group = 'ru.vladify.vshum'
version = '1.2'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'ch.qos.logback:logback-classic:1.4.14'

    // Документация JavaFX
    implementation 'org.openjfx:javafx-controls:17.0.13:sources'
    implementation 'org.openjfx:javafx-fxml:17.0.13:sources'
    implementation 'org.openjfx:javafx-controls:17.0.13:javadoc'
    implementation 'org.openjfx:javafx-fxml:17.0.13:javadoc'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

javafx {
    version = "17.0.13"
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'ru.vladify.vshum.filemerger.Launcher'
}

shadowJar {
    archiveBaseName.set('FileMerger')
    archiveVersion.set('')
    archiveClassifier.set('')
    mergeServiceFiles()

    manifest {
        attributes('Main-Class': 'ru.vladify.vshum.filemerger.Launcher')
    }
}